language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-private-dev libevent-dev libpam0g-dev libwrap0-dev

script:
  - qmake -recursive
  - make
  - cd bin
  - for i in ./tst_*; do ./$i; done
