language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
    - libqt4-dev
    - libqt4-private-dev
    - libevent-dev
    - libpam0g-dev
    - libwrap0-dev

before_install:
  - git submodule update --init --recursive

script:
  - qmake -recursive && make
  - cd bin
  - for i in ./tst_*; do ./$i; done
